/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package airline.system;

import java.sql.Connection;
import java.sql.Date;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author sharayu
 */
public class Acancelbook extends javax.swing.JFrame {

    /**
     * Creates new form Acancelbook
     */
    public Acancelbook() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_info = new javax.swing.JTable();
        view = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        emtx = new javax.swing.JTextField();
        frm = new javax.swing.JComboBox();
        to = new javax.swing.JComboBox();
        da = new com.toedter.calendar.JDateChooser();
        tm = new javax.swing.JComboBox();
        c = new javax.swing.JComboBox();
        cancel = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Email  :");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 230, 50, 20));

        jLabel2.setBackground(new java.awt.Color(0, 0, 0));
        jLabel2.setFont(new java.awt.Font("Rockwell Extra Bold", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Cancel Bookings");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, -1, -1));

        tbl_info.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Email", "From", "To", "Date", "Time", "Class"
            }
        ));
        jScrollPane1.setViewportView(tbl_info);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 630, 90));

        view.setBackground(new java.awt.Color(0, 0, 0));
        view.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        view.setForeground(new java.awt.Color(255, 255, 255));
        view.setText("View");
        view.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewActionPerformed(evt);
            }
        });
        getContentPane().add(view, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 70, -1, 30));

        jLabel3.setBackground(new java.awt.Color(0, 0, 0));
        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("From  :");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 270, -1, -1));

        jLabel4.setBackground(new java.awt.Color(0, 0, 0));
        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("To    :");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 310, 40, -1));

        jLabel5.setBackground(new java.awt.Color(0, 0, 0));
        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Date   :");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 340, -1, 20));

        jLabel6.setBackground(new java.awt.Color(0, 0, 0));
        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Time  :");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 380, 50, -1));

        jLabel7.setBackground(new java.awt.Color(0, 0, 0));
        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Seat Type :");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 410, -1, 30));
        getContentPane().add(emtx, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 220, 200, 30));

        frm.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Pune ", "Mumbai ", "Goa ", "Delhi ", "Bangalore ", "Hyderabad ", "Chandigarh", "Chennai", "Jaipur", "Ahmeadabad", "Kolkata", "Kochin", "Visakhapatnam" }));
        getContentPane().add(frm, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 260, 200, 30));

        to.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Pune ", "Mumbai ", "Goa ", "Delhi ", "Bangalore ", "Hyderabad ", "Chandigarh", "Chennai", "Jaipur", "Ahmeadabad", "Kolkata", "Kochin", "Visakhapatnam" }));
        to.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toActionPerformed(evt);
            }
        });
        getContentPane().add(to, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 300, 200, 30));
        getContentPane().add(da, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 338, 200, -1));

        tm.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "12 AM", "1 AM", "2 AM", "3 AM", "4 AM", "5 AM", "6 AM", "7 AM", "8 AM", "9 AM", "10 AM", "11 AM", "12 PM", "1 PM", "2 PM", "3 PM", "4 PM", "5 PM", "6 PM", "7 PM", "8 PM", "9 PM", "10 PM", "11 PM" }));
        tm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tmActionPerformed(evt);
            }
        });
        getContentPane().add(tm, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 370, 200, 30));

        c.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Economical", "Business" }));
        getContentPane().add(c, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 410, 200, 30));

        cancel.setBackground(new java.awt.Color(0, 0, 0));
        cancel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cancel.setForeground(new java.awt.Color(255, 255, 255));
        cancel.setText("Cancel");
        cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelActionPerformed(evt);
            }
        });
        getContentPane().add(cancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 245, 80, 30));

        jButton1.setBackground(new java.awt.Color(0, 0, 0));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Home");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 20, 80, 40));

        jLabel8.setBackground(new java.awt.Color(0, 0, 0));
        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Cancel Request :");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 76, 130, 20));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/air_image/adm.jpg"))); // NOI18N
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 650, 450));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void toActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_toActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_toActionPerformed

    private void cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelActionPerformed
String email=emtx.getText(); 
      String value=frm.getSelectedItem().toString();
      String value1=to.getSelectedItem().toString();
    //date
      Date date= new Date(da.getDate().getTime());
      DateFormat dateFormat=new SimpleDateFormat("yyyy-mm-dd");
      String strDate=dateFormat.format(da.getDate());
      
      String time=tm.getSelectedItem().toString();
      String value3=c.getSelectedItem().toString();
       

     
     
      
      
      Connection con=null;
        PreparedStatement pst=null;
                try{  
                Class.forName("com.mysql.jdbc.Driver");  
                 con=DriverManager.getConnection("jdbc:mysql://localhost:3306/arilinedb","root","SQL@2020");
                 pst=con.prepareStatement("delete from  bookings where email=? and fromp=? and top=? and dof=? and Timing=? and class=? ");
                pst.setString(1, email);
                pst.setString(2, value);
                pst.setString(3, value1);
                pst.setDate(4,date);
                pst.setString(5, time);
                pst.setString(6,value3);
                               

               
               
                int j= pst.executeUpdate();
          if(j>0)
          {
              JOptionPane.showMessageDialog(null,"booking Canceled ");
          }
          else{
            JOptionPane.showMessageDialog(null,"booking not Cancelled");
          }
                new Uhome().setVisible(true);
       this.setVisible(false);  
                }
                
                
                
                catch(Exception e){ System.out.println(e);} 
                
             
                
               
                try{  
                Class.forName("com.mysql.jdbc.Driver");  
                 con=DriverManager.getConnection("jdbc:mysql://localhost:3306/arilinedb","root","SQL@2020");
                 pst=con.prepareStatement("delete from cancel where email=? and fromp=? and top=? and dof=? and Timing=? and class=? ");
                pst.setString(1, email);
                pst.setString(2, value);
                pst.setString(3, value1);
                pst.setDate(4,date);
                pst.setString(5, time);
                pst.setString(6,value3);
                               

               
               
                int j= pst.executeUpdate();
          if(j>0)
          {
              JOptionPane.showMessageDialog(null,"booking Canceled ");
          }
          else{
            JOptionPane.showMessageDialog(null,"booking not Cancelled");
          }
                new Uhome().setVisible(true);
       this.setVisible(false);  
                }
                
                
                
                catch(Exception e){ System.out.println(e);}
                
                
                
                
                
                
                
                
                
                
                
                
                

           // TODO add your handling code here:
    }//GEN-LAST:event_cancelActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        new Ahome().setVisible(true);
        this.setVisible(false);// TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void viewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewActionPerformed

    
      
    Connection con=null;
        PreparedStatement pst=null;
        ResultSet rs=null;

        try{
            Class.forName("com.mysql.jdbc.Driver");
            con=DriverManager.getConnection("jdbc:mysql://localhost:3306/arilinedb","root","SQL@2020");
            Statement st=con.createStatement();
            String sql="select email,fromp,top,dof,Timing,class from cancel";

            pst=con.prepareStatement(sql);

            
            rs= pst.executeQuery();
            
            while(rs.next())
            {
                                String em= rs.getNString("email");

                String Source= rs.getNString("fromp");
                String top= rs.getNString("top");
                String dof= String.valueOf(rs.getDate("dof"));
                String Timing= rs.getNString("Timing");
                String class1= rs.getNString("class");
               
                
                String tbData[]={em,Source,top,dof,Timing,class1};
                DefaultTableModel tblModel = (DefaultTableModel)tbl_info.getModel();
             
                
                tblModel.addRow(tbData);
            }
            
        con.close();
        }

        catch(Exception e){ System.out.println(e);}
// TODO add your handling code here:
    }//GEN-LAST:event_viewActionPerformed

    private void tmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tmActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tmActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Acancelbook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Acancelbook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Acancelbook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Acancelbook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Acancelbook().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox c;
    private javax.swing.JButton cancel;
    private com.toedter.calendar.JDateChooser da;
    private javax.swing.JTextField emtx;
    private javax.swing.JComboBox frm;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbl_info;
    private javax.swing.JComboBox tm;
    private javax.swing.JComboBox to;
    private javax.swing.JButton view;
    // End of variables declaration//GEN-END:variables
}
