/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package airline.system;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author sharayu
 */
public class Aremove extends javax.swing.JFrame {

    /**
     * Creates new form Abstatus
     */
    public Aremove() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton3 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_info = new javax.swing.JTable();
        view = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        delete = new javax.swing.JButton();
        nm = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        nmtx = new javax.swing.JTextField();
        emtx = new javax.swing.JTextField();
        ad = new javax.swing.JLabel();
        adtx = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton3.setBackground(new java.awt.Color(0, 0, 0));
        jButton3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Home");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 20, -1, 35));

        jLabel8.setBackground(new java.awt.Color(0, 0, 0));
        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Cancel Request :");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 130, 30));

        tbl_info.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "Email", "Mobile No", "Gender", "DOB", "Adhar"
            }
        ));
        jScrollPane1.setViewportView(tbl_info);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 630, 90));

        view.setBackground(new java.awt.Color(0, 0, 0));
        view.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        view.setForeground(new java.awt.Color(255, 255, 255));
        view.setText("View");
        view.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewActionPerformed(evt);
            }
        });
        getContentPane().add(view, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 60, -1, 30));

        jLabel2.setBackground(new java.awt.Color(0, 0, 0));
        jLabel2.setFont(new java.awt.Font("Rockwell Extra Bold", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Remove User");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 3, -1, 40));

        delete.setBackground(new java.awt.Color(0, 0, 0));
        delete.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        delete.setForeground(new java.awt.Color(255, 255, 255));
        delete.setText("Remove");
        delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteActionPerformed(evt);
            }
        });
        getContentPane().add(delete, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 250, 90, 30));

        nm.setBackground(new java.awt.Color(0, 0, 0));
        nm.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        nm.setForeground(new java.awt.Color(255, 255, 255));
        nm.setText("Name             :");
        getContentPane().add(nm, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 260, 100, 30));

        jLabel3.setBackground(new java.awt.Color(0, 0, 0));
        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Email              :");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 310, 100, 30));

        nmtx.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nmtxActionPerformed(evt);
            }
        });
        getContentPane().add(nmtx, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 260, 180, 30));

        emtx.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emtxActionPerformed(evt);
            }
        });
        getContentPane().add(emtx, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 310, 180, 30));

        ad.setBackground(new java.awt.Color(0, 0, 0));
        ad.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        ad.setForeground(new java.awt.Color(255, 255, 255));
        ad.setText("Adhar No.     :");
        getContentPane().add(ad, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 350, 120, 40));
        getContentPane().add(adtx, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 360, 180, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/air_image/adm.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, -4, 650, 450));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        new Ahome().setVisible(true);
        this.setVisible(false);// TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void viewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewActionPerformed

        Connection con=null;
        PreparedStatement pst=null;
        ResultSet rs=null;

        try{
            Class.forName("com.mysql.jdbc.Driver");
            con=DriverManager.getConnection("jdbc:mysql://localhost:3306/arilinedb","root","SQL@2020");
            Statement st=con.createStatement();
            String sql="select name,email,mobile_no,gender,dob,adhar from user_info";

            pst=con.prepareStatement(sql);

            rs= pst.executeQuery();

            while(rs.next())
            {
                   String nm= rs.getNString("name");
                String em= rs.getNString("email");

             
                String mb= rs.getNString("mobile_no");
                String gen= String.valueOf(rs.getDate("gender"));
                String dob= rs.getNString("dob");
                String adhar= rs.getNString("adhar");

                String tbData[]={nm,em,mb,gen,dob,adhar};
                DefaultTableModel tblModel = (DefaultTableModel)tbl_info.getModel();

                tblModel.addRow(tbData);
            }

            con.close();
        }

        catch(Exception e){ System.out.println(e);}
        // TODO add your handling code here:
    }//GEN-LAST:event_viewActionPerformed

    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionPerformed
        String name=nmtx.getText();
         String email=emtx.getText();
          String adhar=adtx.getText();

        Connection con=null;
        PreparedStatement pst=null;
        try{
            Class.forName("com.mysql.jdbc.Driver");
            con=DriverManager.getConnection("jdbc:mysql://localhost:3306/arilinedb","root","SQL@2020");
            pst=con.prepareStatement("delete from  user_info where name=? and email=? and adhar=? ");
            pst.setString(1, name);
            pst.setString(2, email);
            pst.setString(3, adhar);
           

            int j= pst.executeUpdate();
            if(j>0)
            {
                JOptionPane.showMessageDialog(null,"User Removed ");
            }
            else{
                JOptionPane.showMessageDialog(null,"User not Removed");
            }
            new Uhome().setVisible(true);
            this.setVisible(false);
        }

        catch(Exception e){ System.out.println(e);}

        

        // TODO add your handling code here:
    }//GEN-LAST:event_deleteActionPerformed

    private void nmtxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nmtxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nmtxActionPerformed

    private void emtxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emtxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emtxActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Aremove.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Aremove.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Aremove.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Aremove.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Aremove().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ad;
    private javax.swing.JTextField adtx;
    private javax.swing.JButton delete;
    private javax.swing.JTextField emtx;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel nm;
    private javax.swing.JTextField nmtx;
    private javax.swing.JTable tbl_info;
    private javax.swing.JButton view;
    // End of variables declaration//GEN-END:variables
}
