/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package airline.system;

import static java.lang.Integer.parseInt;
import java.sql.Connection;
import java.sql.Date;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;

/**
 *
 * @author sharayu
 */
public class Signup extends javax.swing.JFrame {

    /**
     * Creates new form Uhome
     */
    public Signup() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        nmtx = new javax.swing.JTextField();
        dbtx = new com.toedter.calendar.JDateChooser();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        ptx = new javax.swing.JPasswordField();
        mntx = new javax.swing.JTextField();
        emtx = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        adtx = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        gncm = new javax.swing.JComboBox();
        jButton2 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(650, 450));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Name             :");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 93, 100, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Email              :");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 133, 100, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Mobile No      :");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 160, 100, 30));

        nmtx.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nmtxActionPerformed(evt);
            }
        });
        getContentPane().add(nmtx, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 88, 180, -1));

        dbtx.setDateFormatString("dd MMM YYYY");
        dbtx.setMinSelectableDate(new java.util.Date(-62135785682000L));
        getContentPane().add(dbtx, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 240, 180, 30));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("D.O.B             :");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 240, 100, 30));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Password      :");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 280, 100, 30));

        ptx.setText("jPasswordField1");
        getContentPane().add(ptx, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 280, 180, 30));
        getContentPane().add(mntx, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 160, 180, 30));

        emtx.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emtxActionPerformed(evt);
            }
        });
        getContentPane().add(emtx, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 128, 180, -1));

        jLabel7.setFont(new java.awt.Font("Berlin Sans FB", 1, 36)); // NOI18N
        jLabel7.setText("SIGN UP");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 0, 210, 80));

        jButton1.setBackground(new java.awt.Color(204, 204, 204));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setText("SUBMIT");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 340, 100, 40));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Adhar No.     :");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 310, 120, 40));
        getContentPane().add(adtx, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 320, 180, 30));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("Gender          :");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 200, 100, 30));

        gncm.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Male", "Female" }));
        gncm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gncmActionPerformed(evt);
            }
        });
        getContentPane().add(gncm, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 200, 180, 30));

        jButton2.setBackground(new java.awt.Color(0, 0, 0));
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Home");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 20, 80, 40));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/air_image/a1.jpg"))); // NOI18N
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 650, 450));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

            PreparedStatement stmt = null;

 String name=nmtx.getText();
 String email=emtx.getText();
  if (!(Pattern.matches("^[a-zA-Z0-9]+[@]{1}+[a-zA-Z0-9]+[.]{1}+[a-zA-Z0-9]+$", email.toString()))) 
{
            JOptionPane.showMessageDialog(null, "Please enter a valid email", "Error", JOptionPane.ERROR_MESSAGE);
            new Signup().setVisible(true);
            this.setVisible(false);
            }
            else
            {
 
  String mno = mntx.getText();
  
  String value1=gncm.getSelectedItem().toString(); 
       Date date= new Date(dbtx.getDate().getTime());
      DateFormat dateFormat=new SimpleDateFormat("yyyy-mm-dd");
      String strDate=dateFormat.format(dbtx.getDate());
 String pass=ptx.getText();
  if (   pass.length()<6){
        JOptionPane.showMessageDialog(null,"password must be 6 charector");
        }
        else if(pass.isEmpty()){
        JOptionPane.showMessageDialog(null, "password is empty ");
        }
       
        else{
        
      
 String adhar=adtx.getText();
 
        if(email.isEmpty() || pass.isEmpty() || name.isEmpty() || adhar.isEmpty() || mno.isEmpty() || strDate.isEmpty() ){
      JOptionPane.showMessageDialog(null, "some fields are Empty");
      }
        
        else{
try{
          try {   
              Class.forName("com.mysql.jdbc.Driver");
          } catch (ClassNotFoundException ex) {
              Logger.getLogger(Signup.class.getName()).log(Level.SEVERE, null, ex);
          }
 Connection con =DriverManager.getConnection("jdbc:mysql://localhost:3306/arilinedb","root","SQL@2020");
 stmt =con.prepareStatement("insert into user_info values(?,?,?,?,?,?,?)");
 
 stmt.setString(1,name);
 stmt.setString(2,email);
 stmt.setString(3,mno);
 stmt.setString(4,value1);
 stmt.setDate(5,date);
 stmt.setString(6,pass);
 stmt.setString(7,adhar);
int i=stmt.executeUpdate();
 JOptionPane.showMessageDialog(this,"RECORD ADDED SUCCESSFULLY");
}
 catch(SQLException e){ 
     System.out.println(e);
 }
        }
 }
            }// TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void gncmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gncmActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_gncmActionPerformed

    private void nmtxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nmtxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nmtxActionPerformed

    private void emtxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emtxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emtxActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
new Login().setVisible(true);
        this.setVisible(false);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new Signup().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField adtx;
    private com.toedter.calendar.JDateChooser dbtx;
    private javax.swing.JTextField emtx;
    private javax.swing.JComboBox gncm;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField mntx;
    private javax.swing.JTextField nmtx;
    private javax.swing.JPasswordField ptx;
    // End of variables declaration//GEN-END:variables
}
