/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package airline.system;

import java.sql.Connection;
import java.sql.Date;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;

/**
 *
 * @author sharayu
 */
public class Ucancel extends javax.swing.JFrame {

    /**
     * Creates new form Ucancel
     */
    public Ucancel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        cls = new javax.swing.JComboBox();
        tm = new javax.swing.JComboBox();
        l5 = new javax.swing.JLabel();
        l6 = new javax.swing.JLabel();
        l4 = new javax.swing.JLabel();
        don = new com.toedter.calendar.JDateChooser();
        to = new javax.swing.JComboBox();
        frm = new javax.swing.JComboBox();
        emtx = new javax.swing.JTextField();
        l1 = new javax.swing.JLabel();
        l2 = new javax.swing.JLabel();
        l3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(650, 450));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Berlin Sans FB", 1, 34)); // NOI18N
        jLabel1.setText("Enter your booking details to Cancel");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 600, 40));

        cls.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Economical", "Business" }));
        getContentPane().add(cls, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 340, 210, 32));

        tm.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "12 AM", "1 AM", "2 AM", "3 AM", "4 AM", "5 AM", "6 AM", "7 AM", "8 AM", "9 AM", "10 AM", "11 AM", "12 PM", "1 PM", "2 PM", "3 PM", "4 PM", "5 PM", "6 PM", "7 PM", "8 PM", "9 PM", "10 PM", "11 PM" }));
        tm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tmActionPerformed(evt);
            }
        });
        getContentPane().add(tm, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 300, 210, 32));

        l5.setBackground(new java.awt.Color(0, 0, 0));
        l5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        l5.setText("Time     :");
        getContentPane().add(l5, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 300, -1, 32));

        l6.setBackground(new java.awt.Color(0, 0, 0));
        l6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        l6.setText("Class    :");
        getContentPane().add(l6, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 340, 60, 32));

        l4.setBackground(new java.awt.Color(0, 0, 0));
        l4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        l4.setText("Date     :");
        getContentPane().add(l4, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 260, -1, 32));
        getContentPane().add(don, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 260, 211, 32));

        to.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Pune ", "Mumbai ", "Thane ", "Goa ", "Delhi ", "Bangluru ", "Hyderabad ", "Chandighar" }));
        getContentPane().add(to, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 220, 211, 31));

        frm.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Pune ", "Mumbai ", "Thane", "Goa ", "Delhi ", "Bangluru ", "Hyderabad ", "Chandighar", "Chennai" }));
        getContentPane().add(frm, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 180, 211, 31));
        getContentPane().add(emtx, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 140, 211, 34));

        l1.setBackground(new java.awt.Color(0, 0, 0));
        l1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        l1.setText("Email   :");
        getContentPane().add(l1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 140, -1, 29));

        l2.setBackground(new java.awt.Color(0, 0, 0));
        l2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        l2.setText("Point of Departure   :");
        getContentPane().add(l2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, -1, 31));

        l3.setBackground(new java.awt.Color(0, 0, 0));
        l3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        l3.setText("Destination   :");
        getContentPane().add(l3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 220, -1, 31));

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setText("Request");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(487, 358, 110, 30));

        jButton2.setBackground(new java.awt.Color(0, 0, 0));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Home");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 30, 90, 40));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/air_image/a3.jpg"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 610, 410));

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 650, 450));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tmActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tmActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
new Uhome().setVisible(true); 
this.setVisible(false);// TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
 String email=emtx.getText(); 
      String value=frm.getSelectedItem().toString();
      String value1=to.getSelectedItem().toString();
    //date
      Date date= new Date(don.getDate().getTime());
      DateFormat dateFormat=new SimpleDateFormat("yyyy-mm-dd");
      String strDate=dateFormat.format(don.getDate());
      
      String time=tm.getSelectedItem().toString();
      String value3=cls.getSelectedItem().toString();
      
if(email.isEmpty() || value.isEmpty() || value1.isEmpty() || value3.isEmpty() || time.isEmpty() || strDate.isEmpty() ){
      JOptionPane.showMessageDialog(null, "some fields are Empty can not request not sent");
      }
     
      else
     {
     
     
      
      
      Connection con=null;
        PreparedStatement pst=null;
                try{  
                Class.forName("com.mysql.jdbc.Driver");  
                 con=DriverManager.getConnection("jdbc:mysql://localhost:3306/arilinedb","root","SQL@2020");
                 pst=con.prepareStatement(" insert into cancel (email,fromp,top,dof, Timing,class )values(?,?,?,?,?,?)");
                pst.setString(1, email);
                pst.setString(2, value);
                pst.setString(3, value1);
                pst.setDate(4,date);
                pst.setString(5, time);
                pst.setString(6,value3);
                                

               
               
                int j= pst.executeUpdate();
          if(j>0)
          {
              JOptionPane.showMessageDialog(null,"request sent");
          }
          else{
            JOptionPane.showMessageDialog(null,"request not sent");
          }
                new Uhome().setVisible(true);
       this.setVisible(false);  
                }
                
                
                
                catch(Exception e){ System.out.println(e);}       
     }// TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ucancel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ucancel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ucancel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ucancel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ucancel().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox cls;
    private com.toedter.calendar.JDateChooser don;
    private javax.swing.JTextField emtx;
    private javax.swing.JComboBox frm;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel l1;
    private javax.swing.JLabel l2;
    private javax.swing.JLabel l3;
    private javax.swing.JLabel l4;
    private javax.swing.JLabel l5;
    private javax.swing.JLabel l6;
    private javax.swing.JComboBox tm;
    private javax.swing.JComboBox to;
    // End of variables declaration//GEN-END:variables
}
