/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package airline.system;

/**
 *
 * @author sharayu
 */
public class Uhome extends javax.swing.JFrame {
    /**
     * Creates new form signup
     */
    public Uhome() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        home = new javax.swing.JButton();
        up = new javax.swing.JButton();
        can = new javax.swing.JButton();
        pr = new javax.swing.JButton();
        feb = new javax.swing.JButton();
        cu = new javax.swing.JButton();
        logo = new javax.swing.JButton();
        book = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(650, 450));
        setSize(new java.awt.Dimension(650, 450));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Berlin Sans FB", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText(" starts here...");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 280, 340, 160));

        home.setBackground(new java.awt.Color(0, 0, 0));
        home.setForeground(new java.awt.Color(255, 255, 255));
        home.setText("HOME");
        home.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeActionPerformed(evt);
            }
        });
        getContentPane().add(home, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 110, 40));

        up.setBackground(new java.awt.Color(0, 0, 0));
        up.setForeground(new java.awt.Color(255, 255, 255));
        up.setText("UPDATE");
        up.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                upActionPerformed(evt);
            }
        });
        getContentPane().add(up, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 110, 40));

        can.setBackground(new java.awt.Color(0, 0, 0));
        can.setForeground(new java.awt.Color(255, 255, 255));
        can.setText("CANCEL");
        can.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                canActionPerformed(evt);
            }
        });
        getContentPane().add(can, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, 110, 40));

        pr.setBackground(new java.awt.Color(0, 0, 0));
        pr.setForeground(new java.awt.Color(255, 255, 255));
        pr.setText("PROFILE");
        pr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prActionPerformed(evt);
            }
        });
        getContentPane().add(pr, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, 110, 40));

        feb.setBackground(new java.awt.Color(0, 0, 0));
        feb.setForeground(new java.awt.Color(255, 255, 255));
        feb.setText("FEEDBACK");
        feb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                febActionPerformed(evt);
            }
        });
        getContentPane().add(feb, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, 110, 40));

        cu.setBackground(new java.awt.Color(0, 0, 0));
        cu.setForeground(new java.awt.Color(255, 255, 255));
        cu.setText("CONTACT US");
        cu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cuActionPerformed(evt);
            }
        });
        getContentPane().add(cu, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 320, 110, 40));

        logo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        logo.setText("LOG OUT");
        logo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoActionPerformed(evt);
            }
        });
        getContentPane().add(logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 20, 120, 30));

        book.setBackground(new java.awt.Color(0, 0, 0));
        book.setForeground(new java.awt.Color(255, 255, 255));
        book.setText("BOOK");
        book.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookActionPerformed(evt);
            }
        });
        getContentPane().add(book, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 110, 40));

        jLabel3.setFont(new java.awt.Font("Berlin Sans FB", 1, 48)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Your");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 190, 160, 70));

        jLabel4.setFont(new java.awt.Font("Berlin Sans FB", 1, 48)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("journey");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 260, 210, 50));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/air_image/passanger.jpg"))); // NOI18N
        jLabel5.setMaximumSize(new java.awt.Dimension(650, 450));
        jLabel5.setMinimumSize(new java.awt.Dimension(650, 450));
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 650, 450));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void upActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_upActionPerformed
new Uupdate().setVisible(true);
this.setVisible(false);        // TODO add your handling code here:
    }//GEN-LAST:event_upActionPerformed

    private void canActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_canActionPerformed
       new Ucancel().setVisible(true);
this.setVisible(false); // TODO add your handling code here:
    }//GEN-LAST:event_canActionPerformed

    private void prActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prActionPerformed
        new Uview().setVisible(true);
this.setVisible(false);// TODO add your handling code here:
    }//GEN-LAST:event_prActionPerformed

    private void febActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_febActionPerformed
      new Feedback().setVisible(true);
this.setVisible(false);  // TODO add your handling code here:
    }//GEN-LAST:event_febActionPerformed

    private void cuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cuActionPerformed
       new Contact_us().setVisible(true);
this.setVisible(false); // TODO add your handling code here:
    }//GEN-LAST:event_cuActionPerformed

    private void homeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeActionPerformed
new Uhome().setVisible(true);      // TODO add your handling code here:
    }//GEN-LAST:event_homeActionPerformed

    private void logoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoActionPerformed
new Login().setVisible(true);
this.setVisible(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_logoActionPerformed

    private void bookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bookActionPerformed
      new Ubook().setVisible(true);
this.setVisible(false);  // TODO add your handling code here:
    }//GEN-LAST:event_bookActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Uhome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Uhome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Uhome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Uhome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Uhome().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton book;
    private javax.swing.JButton can;
    private javax.swing.JButton cu;
    private javax.swing.JButton feb;
    private javax.swing.JButton home;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JButton logo;
    private javax.swing.JButton pr;
    private javax.swing.JButton up;
    // End of variables declaration//GEN-END:variables
}
