/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package airline.system;

import java.sql.Connection;
import java.sql.Date;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;

/**
 *
 * @author sharayu
 */
public class Uupdate extends javax.swing.JFrame {

    /**
     * Creates new form Uupdate
     */
    public Uupdate() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        t = new javax.swing.JButton();
        l1 = new javax.swing.JLabel();
        l2 = new javax.swing.JLabel();
        l3 = new javax.swing.JLabel();
        l4 = new javax.swing.JLabel();
        l6 = new javax.swing.JLabel();
        emtx = new javax.swing.JTextField();
        frm = new javax.swing.JComboBox();
        to = new javax.swing.JComboBox();
        don = new com.toedter.calendar.JDateChooser();
        tm = new javax.swing.JComboBox();
        cls = new javax.swing.JComboBox();
        l5 = new javax.swing.JLabel();
        d = new javax.swing.JButton();
        pd = new javax.swing.JButton();
        da = new javax.swing.JButton();
        c = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 48)); // NOI18N
        jLabel1.setText("Want to Change Bookings?");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 580, 68));

        t.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        t.setText("Change");
        t.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tActionPerformed(evt);
            }
        });
        getContentPane().add(t, new org.netbeans.lib.awtextra.AbsoluteConstraints(445, 326, -1, 32));

        l1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        l1.setText("Email   :");
        getContentPane().add(l1, new org.netbeans.lib.awtextra.AbsoluteConstraints(133, 159, -1, 29));

        l2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        l2.setText("Point of Departure   :");
        getContentPane().add(l2, new org.netbeans.lib.awtextra.AbsoluteConstraints(41, 202, -1, 31));

        l3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        l3.setText("Destination   :");
        getContentPane().add(l3, new org.netbeans.lib.awtextra.AbsoluteConstraints(91, 248, -1, 31));

        l4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        l4.setText("Date     :");
        getContentPane().add(l4, new org.netbeans.lib.awtextra.AbsoluteConstraints(129, 287, -1, 32));

        l6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        l6.setText("Class   :");
        getContentPane().add(l6, new org.netbeans.lib.awtextra.AbsoluteConstraints(134, 366, -1, 32));
        getContentPane().add(emtx, new org.netbeans.lib.awtextra.AbsoluteConstraints(198, 157, 211, 34));

        frm.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Pune ", "Mumbai ", "Thane", "Goa ", "Delhi ", "Bangluru ", "Hyderabad ", "Chandighar", "Chennai" }));
        getContentPane().add(frm, new org.netbeans.lib.awtextra.AbsoluteConstraints(198, 203, 211, 31));

        to.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Pune ", "Mumbai ", "Thane ", "Goa ", "Delhi ", "Bangluru ", "Hyderabad ", "Chandighar" }));
        getContentPane().add(to, new org.netbeans.lib.awtextra.AbsoluteConstraints(198, 249, 211, 31));
        getContentPane().add(don, new org.netbeans.lib.awtextra.AbsoluteConstraints(198, 287, 211, 32));

        tm.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "12 AM", "1 AM", "2 AM", "3 AM", "4 AM", "5 AM", "6 AM", "7 AM", "8 AM", "9 AM", "10 AM", "11 AM", "12 PM", "1 PM", "2 PM", "3 PM", "4 PM", "5 PM", "6 PM", "7 PM", "8 PM", "9 PM", "10 PM", "11 PM" }));
        getContentPane().add(tm, new org.netbeans.lib.awtextra.AbsoluteConstraints(198, 327, 210, 32));

        cls.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Economical", "Business" }));
        getContentPane().add(cls, new org.netbeans.lib.awtextra.AbsoluteConstraints(198, 367, 210, 32));

        l5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        l5.setText("Time     :");
        getContentPane().add(l5, new org.netbeans.lib.awtextra.AbsoluteConstraints(128, 326, -1, 32));

        d.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        d.setText("Change");
        d.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dActionPerformed(evt);
            }
        });
        getContentPane().add(d, new org.netbeans.lib.awtextra.AbsoluteConstraints(445, 247, -1, 32));

        pd.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        pd.setText("Change");
        pd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pdActionPerformed(evt);
            }
        });
        getContentPane().add(pd, new org.netbeans.lib.awtextra.AbsoluteConstraints(445, 201, -1, 32));

        da.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        da.setText("Change");
        da.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                daActionPerformed(evt);
            }
        });
        getContentPane().add(da, new org.netbeans.lib.awtextra.AbsoluteConstraints(445, 287, -1, 32));

        c.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        c.setText("Change");
        c.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cActionPerformed(evt);
            }
        });
        getContentPane().add(c, new org.netbeans.lib.awtextra.AbsoluteConstraints(445, 366, -1, 32));

        jButton1.setBackground(new java.awt.Color(0, 0, 0));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Home");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(519, 30, 90, 40));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/air_image/entr.jpg"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 610, 420));

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 650, 450));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tActionPerformed
String email=emtx.getText(); 
      String value=frm.getSelectedItem().toString();
      String value1=to.getSelectedItem().toString();
    //date
      Date date= new Date(don.getDate().getTime());
      DateFormat dateFormat=new SimpleDateFormat("yyyy-mm-dd");
      String strDate=dateFormat.format(don.getDate());
      
      String time=tm.getSelectedItem().toString();
      String value3=cls.getSelectedItem().toString();
     
      
      if(email.isEmpty() || value.isEmpty() || value1.isEmpty() || value3.isEmpty() || time.isEmpty() || strDate.isEmpty() ){
      JOptionPane.showMessageDialog(null, "some fields are Empty can not update bookings");
      }
     
      else
     {
     
     
      
      
      Connection con=null;
        PreparedStatement pst=null;
                try{  
                Class.forName("com.mysql.jdbc.Driver");  
                 con=DriverManager.getConnection("jdbc:mysql://localhost:3306/arilinedb","root","SQL@2020");
                 pst=con.prepareStatement(" update bookings set Timing=? where email=? and fromp=? and top=? and dof=? and class=?" );
                pst.setString(2, email);
                pst.setString(3, value);
                pst.setString(4, value1);
                pst.setDate(5,date);
                pst.setString(1, time);
                pst.setString(6,value3);
               
               
                int j= pst.executeUpdate();
          if(j>0)
          {
              JOptionPane.showMessageDialog(null,"booking updated successfully");
          }
          else{
            JOptionPane.showMessageDialog(null,"booking update not successfully");
          }
                new Uhome().setVisible(true);
       this.setVisible(false);  
                }
                
                
                
                catch(Exception e){ System.out.println(e);}  }      // TODO add your handling code here:
    }//GEN-LAST:event_tActionPerformed

    private void dActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dActionPerformed
      String email=emtx.getText(); 
      String value=frm.getSelectedItem().toString();
      String value1=to.getSelectedItem().toString();
    //date
      Date date= new Date(don.getDate().getTime());
      DateFormat dateFormat=new SimpleDateFormat("yyyy-mm-dd");
      String strDate=dateFormat.format(don.getDate());
      
      String time=tm.getSelectedItem().toString();
      String value3=cls.getSelectedItem().toString();
     
     
     
      
      
      Connection con=null;
        PreparedStatement pst=null;
                try{  
                Class.forName("com.mysql.jdbc.Driver");  
                 con=DriverManager.getConnection("jdbc:mysql://localhost:3306/arilinedb","root","SQL@2020");
                 pst=con.prepareStatement(" update bookings set top=? where email=? and fromp=? and Timing=? and dof=? and class=?" );
                pst.setString(2, email);
                pst.setString(3, value);
                pst.setString(1, value1);
                pst.setDate(5,date);
                pst.setString(4, time);
                pst.setString(6,value3);
               
               
                int j= pst.executeUpdate();
          if(j>0)
          {
              JOptionPane.showMessageDialog(null,"booking updated successfully");
          }
          else{
            JOptionPane.showMessageDialog(null,"booking not updated ");
          }
                new Uhome().setVisible(true);
       this.setVisible(false);  
                }
                
                
                
                catch(Exception e){ System.out.println(e);}   
        // TODO add your handling code here:
    }//GEN-LAST:event_dActionPerformed

    private void pdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pdActionPerformed
    String email=emtx.getText(); 
      String value=frm.getSelectedItem().toString();
      String value1=to.getSelectedItem().toString();
    //date
      Date date= new Date(don.getDate().getTime());
      DateFormat dateFormat=new SimpleDateFormat("yyyy-mm-dd");
      String strDate=dateFormat.format(don.getDate());
      
      String time=tm.getSelectedItem().toString();
      String value3=cls.getSelectedItem().toString();
     
     
     
      
      
      Connection con=null;
        PreparedStatement pst=null;
                try{  
                Class.forName("com.mysql.jdbc.Driver");  
                 con=DriverManager.getConnection("jdbc:mysql://localhost:3306/arilinedb","root","SQL@2020");
                 pst=con.prepareStatement(" update bookings set fromp=? where email=? and timing=? and top=? and dof=? and class=?" );
                pst.setString(2, email);
                pst.setString(1, value);
                pst.setString(4, value1);
                pst.setDate(5,date);
                pst.setString(3, time);
                pst.setString(6,value3);
               
               
                int j= pst.executeUpdate();
          if(j>0)
          {
              JOptionPane.showMessageDialog(null,"booking updated successfully");
          }
          else{
            JOptionPane.showMessageDialog(null,"booking not update ");
          }
                new Uhome().setVisible(true);
       this.setVisible(false);  
                }
                
                
                
                catch(Exception e){ System.out.println(e);}      // TODO add your handling code here:
    }//GEN-LAST:event_pdActionPerformed

    private void daActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_daActionPerformed
      String email=emtx.getText(); 
      String value=frm.getSelectedItem().toString();
      String value1=to.getSelectedItem().toString();
    //date
      Date date= new Date(don.getDate().getTime());
      DateFormat dateFormat=new SimpleDateFormat("yyyy-mm-dd");
      String strDate=dateFormat.format(don.getDate());
      
      String time=tm.getSelectedItem().toString();
      String value3=cls.getSelectedItem().toString();
     
     
     
      
      
      Connection con=null;
        PreparedStatement pst=null;
                try{  
                Class.forName("com.mysql.jdbc.Driver");  
                 con=DriverManager.getConnection("jdbc:mysql://localhost:3306/arilinedb","root","SQL@2020");
                 pst=con.prepareStatement(" update bookings set dof=? where email=? and fromp=? and Timing=? and top=? and class=?" );
                pst.setString(2, email);
                pst.setString(3, value);
                pst.setString(5, value1);
                pst.setDate(1,date);
                pst.setString(4, time);
                pst.setString(6,value3);
               
               
                int j= pst.executeUpdate();
          if(j>0)
          {
              JOptionPane.showMessageDialog(null,"booking updated successfully");
          }
          else{
            JOptionPane.showMessageDialog(null,"booking not updated ");
          }
                new Uhome().setVisible(true);
       this.setVisible(false);  
                }
                
                
                
                catch(Exception e){ System.out.println(e);}    // TODO add your handling code here:
    }//GEN-LAST:event_daActionPerformed

    private void cActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cActionPerformed
       String email=emtx.getText(); 
      String value=frm.getSelectedItem().toString();
      String value1=to.getSelectedItem().toString();
    //date
      Date date= new Date(don.getDate().getTime());
      DateFormat dateFormat=new SimpleDateFormat("yyyy-mm-dd");
      String strDate=dateFormat.format(don.getDate());
      
      String time=tm.getSelectedItem().toString();
      String value3=cls.getSelectedItem().toString();
     
     
     
      
      
      Connection con=null;
        PreparedStatement pst=null;
                try{  
                Class.forName("com.mysql.jdbc.Driver");  
                 con=DriverManager.getConnection("jdbc:mysql://localhost:3306/arilinedb","root","SQL@2020");
                 pst=con.prepareStatement(" update bookings set class=? where email=? and fromp=? and Timing=? and dof=? and top=?" );
                pst.setString(2, email);
                pst.setString(3, value);
                pst.setString(6, value1);
                pst.setDate(5,date);
                pst.setString(4, time);
                pst.setString(1,value3);
               
               
                int j= pst.executeUpdate();
          if(j>0)
          {
              JOptionPane.showMessageDialog(null,"booking updated successfully");
          }
          else{
            JOptionPane.showMessageDialog(null,"booking not updated ");
          }
                new Uhome().setVisible(true);
       this.setVisible(false);  
                }
                
                
                
                catch(Exception e){ System.out.println(e);}   // TODO add your handling code here:
    }//GEN-LAST:event_cActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
new Uhome().setVisible(true);
        this.setVisible(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Uupdate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Uupdate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Uupdate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Uupdate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Uupdate().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton c;
    private javax.swing.JComboBox cls;
    private javax.swing.JButton d;
    private javax.swing.JButton da;
    private com.toedter.calendar.JDateChooser don;
    private javax.swing.JTextField emtx;
    private javax.swing.JComboBox frm;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel l1;
    private javax.swing.JLabel l2;
    private javax.swing.JLabel l3;
    private javax.swing.JLabel l4;
    private javax.swing.JLabel l5;
    private javax.swing.JLabel l6;
    private javax.swing.JButton pd;
    private javax.swing.JButton t;
    private javax.swing.JComboBox tm;
    private javax.swing.JComboBox to;
    // End of variables declaration//GEN-END:variables
}
